---
title: "Results" 
author: "Kendra Wyant"
date: "`r lubridate::today()`"
format: 
  html: 
    embed-resources: true
    toc: true 
    toc_depth: 4
bibliography: references.bib
editor_options: 
  chunk_output_type: console
--- 

```{r}
#| echo: false

options(knitr.kable.NA = '')
```


## Results

### Participant Characteristics
A total of 336 participants enrolled in our study and provided at least one month of data. [@tbl-demo] presents the demographic and clinical characteristics of these participants. 

{{< embed notebooks/mak_demo_table.qmd#tbl-demo >}}


### Adherence

#### Participation
A total of 336 participants enrolled in our study and provided at least one month of EMA data. @fig-1 shows participant attrition over 12 months. There was no significant difference in mean days on study between participants who were non-Hispanic White (*N* = 247, *M* = 299, *SD* = 109) and participants who were not White (*N* = 89, *M* = 284, *SD* = 112), *t*(334) = -1.11, *p* = .27. There was no significant difference in mean days on study between participants who reported a lapse (*N* = 1 37, *M* = 296, *SD* = 107) and those who did not report a lapse (*N* = 199, *M* = 294, *SD* = 112) while on study, *t*(334) = -0.19, *p* = .85.

{{< embed notebooks/ana_adherence.qmd#fig-1 >}}



#### Monthly and Daily Updates
The overall adherence for the monthly updates was extremely high. Participants completed 96% of the monthly updates. 

The overall adherence for the daily updates was 72%. This rate is consistent with other shorter-term EMA protocols in substance use populations (Average adherence is 75% [@jonesComplianceEcologicalMomentary2019]). @fig-2 shows the overall adherence rates for the daily update by month on study. 

There was no significant difference in daily update adherence rates between participants who were non-Hispanic White (*M* = .72, *SD* = .19) and participants who were not white (*M* = .70, *SD* = .19), *t*(334) = -0.88, *p* = .38. There was a significant difference in adherence rates between participants who reported a lapse (*M* = .69, *SD* = .19) and participants who did not report a lapse (*M* = .74, *SD* = .18) while on study, *t*(334) = 2.4, *p* = .02. Participants who reported a lapse, had on average 5% lower adherence compared to participants who did not report a lapse while on study. 


{{< embed notebooks/ana_adherence.qmd#fig-2 >}}


### Participant Experience Questionannaire Quantitative Results
247 participants provided at least four months of data and completed the participant experience questionnaire. These participants were included in following analyses.


#### Interference
84% of participants (*N* = 207/247) disagreed (i.e., endorsing "Strongly disagree" or "Mildly disagree") with the statement "Completing the daily update interfered with my daily activities". 79% of participants (*N* = 196/247) disagreed with the statement "Completing the monthly update interfered with my daily activities". We provide histograms of participant responses in the supplement.   

An ICC (type 3) showed that, on average, interference ratings were moderately consistent across the two updates, ICC = .50, 95% CI = [.40 - .59].


#### Dislike
85% of participants (*N* = 211/247) disagreed (i.e., endorsing "Strongly disagree" or "Mildly disagree") with the statement "I disliked completing the daily update". 73% of participants (*N* = 179/246) disagreed with the statement "I disliked completing the monthly update". Fewer participants disagreed with the statement "I disliked [sensing method]" for geolocation (65%; *N* = 161/247), SMS and phone logs (64%; *N* = 158/246), and SMS content (64%; *N* = 156/245). As a result we saw an increase in responses endorsing a neutral stance toward these passive sensing methods ("Agree and disagree equally"). We provide histograms of participant responses by sensing method in the supplement.   

An ICC (type 3) showed that, on average, dislike ratings were moderately consistent across sensing methods, ICC = .48, 95% CI = [.42 - .54].


### Participant Experience Questionannaire Qualitative Results

#### Thematic Analysis

##### Proportion of Positive Comments by Race/Ethnicity
{{< embed notebooks/figures.qmd#fig-pos >}}

##### Proportion of Negative Comments by Race/Ethnicity
{{< embed notebooks/figures.qmd#fig-neg >}}

##### Proportion of Benefits Comments by Race/Ethnicity
{{< embed notebooks/figures.qmd#fig-benefits >}}

##### Proportion of Trust Comments by Race/Ethnicity
{{< embed notebooks/figures.qmd#fig-trust >}}



#### Topic Modeling?
