---
title: "PREP expectations"
format: html
---

## Expectations for Undergraduate Students

1. **Weekly updates of progress.** In our weekly meetings, be prepared to give me a brief description of what you have been working on for the week and where you have been spending most of your time. During this time you can also note any issues that have come up while coding or working on your project.  

2. **Communicate in a timely manner.** I do not expect you to respond on weekends or after work hours during the week. Please try to respond to respond within 48 hours and I will do the same. All communication related to your work in the lab will take place on slack or in-person.

3. **Let me know if you need anything from me as a mentor, or if you have questions.** Be up front and I will do the same. For example, if there is something about my mentoring style that isn’t clicking well with you, please tell me so that you give me an opportunity to find an approach that works for you. 

4. **Attend lab meetings.** The entire lab meets approximately once a week. The topic and any required readings or materials to review will be communicated ahead of time on slack. Please come prepared to participate in the discussion (e.g., asking clarification questions or suggesting an area to discuss that you found interesting). 

5. **Efficient time management.** Your work hours should consistently, efficiently be used to complete tasks that clearly benefit the project or for useful professional development experiences. I will not check-in on you for every shift when you come in for lab hours, but I expect you to show up for your designated lab hours, and to be productively working without supervision during that time. If it ever feels unclear about what you should be doing, or if you feel like you are running out of tasks to do, please reach out to me. Don’t hesitate to let me know if you need additional things to work on, but I also encourage you to suggest tasks to me that you think would be useful (to yourself and to the project!).

6. **Be independent.** Always feel free to ask questions when I am around or over Slack, but don’t be afraid to try to do detective work on your own (e.g., looking at the project manual in `P:/studydata/risk2`). 

7. **Pay attention to details.** Double check your work for accuracy, completeness, and consistency. Double check our project materials and data for errors and inconsistencies, fix them when appropriate and note them in detail. 

8. **Maintain detailed, organized, and accurate notes.**  Note-taking is incredibly valuable; very few people can remember all of the details of things. Additionally, detailed notes documenting any errors or unexpected findings and how you resolved these discrepancies during data cleaning, EDA, and your analyses is critical. I would also recommend taking notes when reading articles to improve your understanding and facilitate our discussions later. 

9. **Maintain appropriate boundaries.** To maintain healthy work-life balance and avoid dual-relationships that could result in conflicts of interest, it is important to maintain appropriate personal-professional boundaries. During your time on the project I will play the role of your supervisor and professional mentor, which naturally presents a power differential. It is my responsibility to make sure that this power differential does not pressure you or exploit you in any way (e.g.  you feeling pressured to undertake additional work, participate in non-academic events, etc.).  First and foremost, my goal is to be a kind, supportive mentor who fosters a close professional working relationship. 

10. **If you are struggling with anything in your personal life which will impact your work, please share that this is a concern as well as what changes to your work on the project may help.  Don’t feel like you need to share details. I am also happy to connect you with further resources if you are struggling.**


## Olivia's Notes

1. **Weekly Task List.** In my lab at VT, my mentor would send an email every Sunday night with a list of tasks/expectations for the week for the RAs. I found this useful as I had something to refer back to during the week and I'm a "to do" list person. The list of tasks doesn't have to be incredibly detailed, just a simple explanation of the tasks that need to be completed. 

2. **My learning style.** I'm a visual learner. I usually need to see a new task done 2 times and then I understand. I'll probably have some questions, but I understand things a lot better when I see them being done rather than being told how to do it. 

3. **Life after Undergrad Help.** I know this is something we'd already discussed, but I'd love some help on polishing my CV and how to stand out on grad school/post-bacc/job applications. I already have a few grad programs I'm interested in, but I'm unsure where to look for post-bacc positions and jobs. In addition, I'd like to know if there are any positions or work I should pursue in undergrad to add to my CV (more clinical experience, TAing experience, etc>)

4. **Professional Development/Research Experience.** I'm very appreciative of the opportunity to give an oral presentation at the end of this summer! I've only done poster presentations up until this point and am looking forward to a new challenge. In addition, I know we had discussed the possibility of drafting a paper and conference travel. I'd love to talk more about this! Even if a paper for this project doesn't happened, I'd like to discuss what goes into writing a a paper of this nature. 

5. **Being in a shared lab space.** I'm a very shy person and it takes me awhile to warm up to others. I've been told that I can seem "standoffish" or rude because of my shyness. I promise that that is not the case at all, I'm just a little socially anxious. Once I'm comfortable, I can talk a lot lol. 

6. **Eyesight/brain issues.** The reason I wear glasses is because of a concussion I had when I was little that did some damage to my occipital lobe. Due to that, staring at screens for an extended period of time really bothers my eyes, gives me a headache, and affects my vision. Occasionally, I do have to take a break so I may look down from the screen, need a minute to rub my eyes, or take a short 5-min walk. 


