---
title: "Introduction"
author: "Olivia Cox"
date: "July 10th, 2024"
format: html
bibliography: references.bib 
---

## Opioid Use Disorder (prevalence)
- Opioid use disorder is defined as the chronic use of opioids that cause clinically significant distress or impairment, affecting over 2.1 million people in the United States [@dydykOpioidUseDisorder2024]. 

## Barriers to Treatment for OUD 
- Individual barriers include a flawed justice system, lack of social support, and unwillingness to change [@mcleanThinkWeRe2024].
- Provider/institutional barriers include low treatment availability in rural areas, absence of psychiatric care and counseling, low variety of treatment options, provider burnout, and system navigation [@mcleanThinkWeRe2024].
- Societal/systemic barriers include laws surrounding methadone treatment, eligibility for public insurance, "war on drugs", stigma, and lack of education about addiction [@mcleanThinkWeRe2024].
- self-guided opioid monitoring technology found relatively high acceptability among participants [@lyzwinskiUsersAcceptabilityPerceived]. 

## Demographic Differences
- The demographic differences we chose to focus on were location, race, age, gender, and SES.
- Location (urban, suburban, rural) plays a huge factor in accessibility to treatment and trust of local authorities. In urban populations, such as Philadelphia, PA, distrust of the police may result in bystanders not intervening when someone is experiencing an overdose [@marcuAcceptabilitySmartphoneApplications2019]. While in rural areas, limited availability of medication treatment has led to overdose-related deaths surpassing urban overdose-related deaths in 2015 [@isterSystematicReviewRuralspecific2020].
- Past research has demonstrated that African Americans and other historically marginalized groups are less likely than White people to receive medication, live near a provider of such medications, or continue treatment for opioid use disorder [@barnettRacialInequalityReceipt2023]. 
- Due to federal regulations, adolescents are less likely than adults to receive medication-based treatment for opioid use disorder, greatly limiting their access to care [@mintzAgeDisparitiesSixmonth2020]. 
- In comparison to men, women face unique barriers when it comes to treatment for opioid use disorder. Women have higher rates of comorbid depression and anxiety, poorer quality of life, stigma, and are more likely to be prescribed psychiatric medications [@dipaolaGenderDifferencesPersons2022]. 
- Individuals of a lower SES are less likely to be treated or be referred for treatment for opioid use disorder [@siddiquiOpioidUseDisorder2022]. 

## Scalable, Digital Therapeutics
- work on this later

## Acceptability of Personal Sensing
- Previous work has shown that these methods are acceptable by those with alcohol use disorder [@wyantAcceptabilityPersonalSensing]. 
- There are reasons to suspect this could be different among those with other substance use disorders, particularly opioid use disorder. As opioids are an illegal class of drugs, individuals may fear judgement or being arrested when entering into treatment. 


## Goals of Study
- Assess if individuals with opioid use disorder from a national sample find personal sensing methods to be an acceptable method of treatment. 
- Use traditional thematic analysis and two machine learning methods, topic modeling and natural language processing with LIWC, to pull out relevant themes from participants' comments. 
- Observe if these themes differ between different demographic groups. 
