---
title: "PREP literature review"
format: html
---

## Literature Review

### Types of Studies

- Reviews: 1

- Empirical: 15

- Sample Type: Clinical (13/15), Community (1/15), Clinical + Community (1/15)

- Substance being studied: Opioids (15/16), Alcohol (4/16), Stimulants (3/16), Cannabis (2/16). Polysubstances (1/16)

### Acceptabilty and Opioid Use Disorder

- Trust was a common concern across studies. Participants noted that they would prefer a healthcare professional they knew and would want to continue working with them in addition to using a mobile health intervention. 


- In terms of wearable devices, most participants in studies stated they would wear a device while taking opioids and would prefer a watch/bracelet. 


- Common features participants enjoyed or would like to have seen are community message boards, secure messaging with a healthcare provider, and access to local resources (meetings, healthcare, housing, etc.)


- Digital health interventions should be of adequate length, not too repetitive, and easy to understand by a diverse group of adults (race, ethnicity, SES, where they're at in treatment, etc.)


- Tasks administered by the digital health intervention should be able to be completed at home or in the clinic and be motivating/engaging enough to keep the participants accountable. 


- One study noted that the messages sent by the app or healthcare providers should be personalized, sent 2-3 times per day, and include multimedia. 


- The majority of these studies were hypothetical. Only 7 of these studies yielded EMA data. The data is:

1.  Wyant et.al: 80%

2.  Waselewski et. al: 86.13%

3.  Hodges et. al: 100% for first month, 76% for sixth month

4.  Hawk et. al: 97% for baseline, 49% for 3-day, 42% for 30-day

5.  Tofighi et. al: 88% responded to at least one text

6.  Zhang et. al: 63% completed the task all 5 days

7.  Godersky et. al: 18-96%; average was 72%

### Questions still from literature

- Most of the populations in these studies (13/15) were clinical. Would answers or ideas have differed if they had asked community or student populations? Or even just people who use substances but can't be diagnosed with a SUD?


- With the addition of a mobile health intervention, how often would participants want to see their healthcare provider? The same as before the intervention, less often, or more often?


- How much should the resources being offered differ between groups? In the study of all women, they noted an interest in parenting advice and how to be respectful towards women in recovery. Would men want parenting advice? How could this be different between racial and ethnic groups?


- Does the location of the study play a large impact in the results? For example, it was noted that Philadelphia, PA has one of the highest overdose rates in the country, and participants in this study noted concerns with law enforcement. How would this study look if it had been conducted in New England, the West Coast, or even a different country?


### Notes from Kendra
These are great questions. I love how you are thinking about how the results may or may not generalize to other groups. On thing that stands out to me is that we did not have a health care provider involved with data collection and data monitoring. It seems like this might be important for building trust with the app. 

One question I have is did these individuals all engage with the personal sensing measures they were asked about? Or were some of these studies hypothetical? (e.g., would you be willing to use XYZ). This could be a limitation of previous studies.
