---
title: Olivia's Mak Burden Notes
format: html
---


### Daily Updates Comments


- Some issues with app (glitches, constant reminders, shuts down randomly, issues going through the questions, failts to submit, etc.)


- Many people noted that it helped with their recovery and they found it be beneficial.


- Easy to complete, doesn't take too much time, and something you can easily add into your daily routine. 


- Provides structure and helps keep participants accountable. 


- Helps participants to express emotions and focus on the good. 


- Some found that having the same questions in the same order everyday was repetitive and had them answering on "autopilot". Maybe rotate order of questions, add in new questions, or change it to a weekly check-in?


- Helps participants stay sober or use less.


- Many participants noted their appreciation towards the app and research staff. 


- Some noted the addition of a notes section each day would be beneficial so they can go back and see what happened each day while preparing for the monthly update or feedback.


- Participants noted it encouraged them to take a daily inventory and actually think and focus on their recovery. 


### Video Check-In Comments


- A few noted that they disliked the "rose, bud, thorn" system as it felt "silly and repetitive". 


- Some noted that it was hard to think of something to share everyday that took the length of the video. 


- Many participants noted that they wished it was just a voice recording as they didn't like having to show their face.


- Some noted it was hard to find alone time to complete them.


- Some noted it was similar to the daily check-ins where it helped them to reflect on their day and/or their recovery. In addition, it provided structure and made them accountable.


- Some noted they didn't like them at all and/or just didn't do them.


- Few noted some technical issues with this activity (video wouldn't upload, it would delete itself, etc.)


- Some participants missed the video check-ins after they were discontinued. 


### Monthly Update Comments


- VERY glitchy. Many people noted that they would be asked to do it multiple times a month, it would skip questions, the app would crash, or kick them out multiple times. 


- Some participants noted that questions were a bit too personal and uncomfortable. 


- Helps participants to look back on their recovery in a detailed way and they found it to be a positive experience.


- Some participants noted that it could be very time consuming, an overall pain, repetitive, and didn't like doing it.


- Similar to the daily check-ins, participants noted it reminded and encouraged them to stay sober. 


- Few noted issues and discrepancies with the phone numbers and GPS locations the check-in listed. 


- Participants would get annoyed if they had to search through messages and call list to find numbers or think hard about the addresses. 


- Some participants noted that they enjoyed it and felt they were contributing to the world in a positive way. 


- Encouraged participants to take inventory of the past month and think about what people, places, and things help them and what doesn't. 


- Despite its length, many participants understood the importance of completing this task.


### GPS Comments


- Most participants didn't mind sharing their GPS data. 


- Some participants noted that they didn't like how fast location tracking drained their battery.


- Some participants stated that while they didn't like having their location tracked, they knew it was for the good of the study and would be beneficial in helping themselves and future substance users. 


- Some participants said that they didn't like being tracked and it wasn't anyone's business where they were. 


- Some participants noted that seeing where they had been played an active role in their recovery (reminded them where they should and should not be and accountability and structure.)


- Some participants noted that they didn't care/it wasn't a burden as they forgot they were being tracked, trusted the researchers, and that other apps on their phone are already tracking them anyway. 


- A few participants noted some issues with the GPS's precision and accuracy (give multiple locations within 1,00 feet, only show gas stations, get addresses wrong, etc.)


### SMS Phone Logs and Content Comments


- Most participants didn't mind/care about sharing their phone logs and message content due to trusting the researchers, not having anything to hide, and/or not using their phone frequently. 


- Similar to GPS, some participants noted that while they were uncomfortable with their phone logs and message content being shared, they understood it was for the greater good of the study and/or benefited their recovery. 


- Some participants did note it was an invasion of their privacy and made them uncomfortable. 


- Some participants did state that they were worried/concerned about getting themselves or the people they're contacting in trouble based off phone logs and message content. 


- Some participants had concerns with the phone numbers used in the monthly updates as they would be spam numbers, business numbers, or unsaved contacts they had to search for. 
