---
title: Notes
editor_options: 
  chunk_output_type: console
---

- 336 particpants with EMA data
- Burden data from 247 participants. 
- All participants provided EMA data for at least 4 months.
- All participants provided quant data
- 222 provided qual data (205 provided comments that were coded)
- We coded a total of 713 comments from 205 participants. We filtered out comments that equate to NA (e.g., None, No, Na, No comment).
- participants completed survey on average after being on study for 4 months (range = 62-142 days)

- quant and qual analyses will specifically look at several demographic characteristics to see if these characteristics have an effect on perceived and objective measures of acceptability.  

Primary variables for analyses:    

- race (Non-Hispanic White, Black, Hispanic, Other)
- gender (male, female)
- income (less than \$25000, more than \$25000)
- location (still need to work on adding this data)
- number of lapses on study up until the start time of the burden survey