---
title: "check_discrepancies"
author: Kendra and Olivia
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

## Notes

This code will be used to check for discrepancies between our thematic coding of comments from the burden survey.

## Set up

```{r}
#| include: false

options(conflicts.policy = "depends.ok")
library(tidyverse) 
library(tidytext)
library(dplyr)

devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/format_path.R?raw=true")

theme_set(theme_classic())

path_prep <- format_path("studydata/risk2/data_processed/prep")
```

## Read in data

```{r}
olivias_codes <- read_csv(file.path(path_prep, "qual_data_codes_OC.csv"),
                          show_col_types = FALSE)
kendras_codes <- read_csv(file.path(path_prep, "qual_data_codes_KW.csv"),
                          show_col_types = FALSE)
comments <- read_csv(file.path(path_prep, "final_comments.csv"),
                          show_col_types = FALSE)
```

## Filter down to final comments

```{r}
kendras_codes <- kendras_codes |> 
  select(-complete_date) |> 
  right_join(comments, by = c("subid", "user_survey_guid", "data",
                              "answer")) 
```

```{r}
olivias_codes <- olivias_codes |> 
  select(-complete_date) |> 
  right_join(comments, by = c("subid", "user_survey_guid", "data", "answer"))
```

## Rename columns

```{r}
kendras_codes <- kendras_codes |> 
  rename_with(~str_c(., "_KW"), acceptability:`neutral/mixed`)
```

```{r}
olivias_codes <- olivias_codes |> 
  rename_with(~str_c(., "_OC"), acceptability:`neutral/mixed`)
```

## Join datasets

```{r}
kendras_codes <- kendras_codes %>%
  arrange(subid, data)

olivias_codes <- olivias_codes %>%
  arrange(subid, data)

kendras_codes_selected <- kendras_codes %>%
  select("acceptability_KW", "sustainability_KW", "benefits_KW", "trust_KW", "usability_KW", "feedback_KW", "positive_KW", "negative_KW", "neutral/mixed_KW")

merged_data <- bind_cols(olivias_codes, kendras_codes_selected)
print(merged_data)
```

## Check for discrepancies

```{r}
benefits <- merged_data %>%
  filter(benefits_OC != benefits_KW) %>%
  select(subid, answer, "benefits_OC", "benefits_KW") %>%
  mutate(benefits_resolve = "") %>% 
  write_csv(file.path(path_prep, "benefits_discr.csv"))
```

```{r}
sustainability <- merged_data %>%
  filter(sustainability_OC != sustainability_KW) %>%
  select(subid, "answer", "sustainability_OC", "sustainability_KW") %>%
   mutate(sustainability_resolve = "") %>% 
  write_csv(file.path(path_prep, "sustainability_discr.csv"))
```

```{r}
trust <- merged_data %>%
  filter(trust_OC != trust_KW) %>%
  select(subid, answer, "trust_OC", "trust_KW") %>%
   mutate(trust_resolve = "") %>% 
  write_csv(file.path(path_prep, "trust_discr.csv"))
```

```{r}
acceptability <- merged_data %>%
  filter(acceptability_OC != acceptability_KW) %>%
  select(subid, answer, "acceptability_OC", "acceptability_KW") %>%
   mutate(acceptability_resolve = "") %>% 
  write_csv(file.path(path_prep, "acceptability_discr.csv"))
```

```{r}
usability <- merged_data %>%
  filter(usability_OC != usability_KW) %>%
  select(subid, answer, "usability_OC", "usability_KW") %>%
   mutate(usability_resolve = "") %>% 
  write_csv(file.path(path_prep, "usability_discr.csv"))
```

```{r}
feedback <- merged_data %>%
  filter(feedback_OC != feedback_KW) %>%
  select(subid, answer, "feedback_OC", "feedback_KW") %>%
   mutate(feedback_resolve = "") %>% 
  write_csv(file.path(path_prep, "feedback_discr.csv"))
```

```{r}
positive <- merged_data %>%
  filter(positive_OC != positive_KW) %>%
  select(subid, answer, "positive_OC", "positive_KW") %>%
   mutate(positive_resolve = "") %>% 
  write_csv(file.path(path_prep, "positive_discr.csv"))
```

```{r}
negative <- merged_data %>%
  filter(negative_OC != negative_KW) %>%
  select(subid, answer, "negative_OC", "negative_KW") %>%
   mutate(negative_resolve = "") %>% 
  write_csv(file.path(path_prep, "negative_discr.csv"))
```

```{r}
neutral_mixed <- merged_data %>%
  filter(`neutral/mixed_OC` != `neutral/mixed_KW`) %>%
  select(subid, answer, "neutral/mixed_OC", "neutral/mixed_KW") %>%
   mutate(`neutral_mixed_resolve` = "") %>% 
  write_csv(file.path(path_prep, "neutral_mixed_discr.csv"))
```
