---
title: "Make final comments" 
author: "Kendra Wyant"
date: "`r lubridate::today()`"
format: 
  html: 
    embed-resources: true
    toc: true 
    toc_depth: 4
editor_options: 
  chunk_output_type: console
---   

## Notes



## Set up
```{r}
#| include: false

options(conflicts.policy = "depends.ok")
library(tidyverse) 
library(janitor)

devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/format_path.R?raw=true")

theme_set(theme_classic())

path_burden <- format_path("risk2/data_processed/burden2")
```

## Read in data

```{r}
comments <- read_csv(here::here(path_burden, "final_comments.csv"),
                         show_col_types = FALSE) |> 
  glimpse()

```

Save out batches
```{r}
comments |> 
  mutate(benefits_self = "",
         benefits_other = "",
         privacy = "",
         research_context = "",
         feasibility = "",
         technology = "") |> 
  slice(1:200) |> 
  write_csv(here::here(path_burden, "coded_comments_1_200_EL.csv")) |> 
  glimpse()
```



