---
title: "Preregistration" 
author: "Kendra Wyant"
date: "`r June 18, 2026"
number-sections: false
embed-resources: true
format: 
 html: 
   toc: false
editor_options: 
  chunk_output_type: console
---


# Data Analysis Plan

## Participation and Adherence

For all enrolled participants we will calculate two behavioral indicators of acceptability with the study protocol. 

1. We will report the overall average length of participation in days. We will also plot monthly retention rates over the course of the 12-month study. 

2. We will report overall and monthly adherence rates for the 2 active personal sensing methods (daily and monthly surveys). We will not calculate adherence for our three passive sensing methods (geolocation, cellular communication logs and SMS text message content) because it is not possible to determine whether missing data was due to non-adherence (e.g., disabling sharing permissions) or other reasons (e.g., infrequent communications with other people, phone in battery-saving mode, poor connection with cellular service).

We will evaluate whether length of study participation differed across our 4 demographic subgroups (gender, race/ethnicity, income, and geographic location) to understand whether certain subgroups were better able and more willing to adhere to the study protocol. Specifically, we will conduct a single linear model where length of participation (in days) is regressed on the four demographic grouping variables (centered around 0). 

`study_days ~ 1 + gender_centered + race_centered + income_centered + geography_centered`


We will not assess for subgroup differences in daily and monthly survey adherence rates to minimize the number of analyses. Participants were withdrawn from the study if adherence dropped, thus differences in adherence will likely also be captured in length of participation. 

## Participant Experience Questionannaire Quantitative Analyses

Participants rated how much they agreed with 7 statements about sensing method interference and dislike using a 5-point scale with descriptive anchors (strongly agree, agree, agree and disagree equally, disagree, or strongly disagree). We recoded these items to a numeric scale ranging from −2 to 2, with 0 representing the neutral (agree and disagree equally) midpoint and higher scores representing greater acceptability. 

### Interference

2 linear models (daily updates and monthly updates)

`interfere ~ 1 + gender_centered + race_centered + income_centered + geography_centered`

Interpretation:

- Overall ratings of interference (are ratings, on average, different than neutral/0)
- Demographic effects (are ratings, on average, different across demographic groups)


### Dislike

5 linear models (daily updates, monthly updates, gps, SMS/phone logs, SMS content)

`dislike ~ 1 + gender_centered + race_centered + income_centered + geography_centered`

Interpretation:

- Overall ratings of dislike (are ratings, on average, different than neutral/0)
- Demographic effects (are ratings, on average, different across demographic groups)


## Participant Experience Questionannaire Qualitative Analyses

We used thematic analysis to analyze participants’ open-ended comments about the personal sensing methods. This is a systematic approach for identifying, analyzing, and reporting patterns or themes within qualitative data.  It uses domain expertise from the literature to create a codebook of thematic categories driven by the aims and questions of the research being conducted. As coding is underway, the codebook is iteratively revised to include additional themes or exclude themes not present in the data.The comments were coded by two independent coders. A third coder was brought in when discrepancies arose and these cases were discussed as a group to arrive at a resolution. We report on 4 primary themes: benefits to self, benefits to others, privacy, and feasibility. Each theme was coded on an ordinal scale of -1 (negative), 0 (neutral or not endorsed), or 1 (positive). 


### Theme Analyses
20 ordinal logistic regression models for each theme (benefits to self, benefits to others, privacy, and feasibility) x sensing method (daily update, monthly update,
gps, phone/sms logs, sms content) combination.

`theme ~ 1 + gender_centered + race_centered + income_centered + geography_centered`


Interpretation:

- Overall log-odds of theme being endorsed (i.e., different from 0 in positive or negative direction)
- Demographic effects (are log-odds of endorsing theme different by demographic group)

